<?xml version="1.0" encoding="utf-8"?>
<Database Name="SDControl" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MICROSOF-C63F18\SQLEXPRESS;Initial Catalog=SDControl;Integrated Security=True" SettingsObjectName="ALProjects.Data.DataAccessLevel.Properties.Settings" SettingsPropertyName="SDControlConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.cmn_user_info" Member="cmn_user_infos">
    <Type Name="cmn_user_info">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Addres" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ICQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Site" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastVisit" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="cmn_user_info_scr_user" Member="scr_users" OtherKey="UserId" Type="scr_user" />
      <Association Name="scr_role_cmn_user_info" Member="scr_role" ThisKey="Role" Type="scr_role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.scr_roles" Member="scr_roles">
    <Type Name="scr_role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rights" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="scr_role_cmn_user_info" Member="cmn_user_infos" OtherKey="Role" Type="cmn_user_info" />
    </Type>
  </Table>
  <Table Name="dbo.scr_users" Member="scr_users">
    <Type Name="scr_user">
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="cmn_user_info_scr_user" Member="cmn_user_info" ThisKey="UserId" Type="cmn_user_info" IsForeignKey="true" />
    </Type>
  </Table>
</Database>